name: CI

on:
  push:
    branches: [ github_actions_test ]
  pull_request:
    branches: [ github_actions_test ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        ruby-version: [2.3.1, 2.7.0]
        include:
          - ruby-version: head
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
